version: 1.0.{build}
image: Visual Studio 2019
build_script:
- cmd: >-
    dotnet tool restore

    dotnet pack src\BingImageDownload.sln --configuration Release
test: off
artifacts:
- path: src\BingImageDownload\nupkg\BingImageDownload.$(appveyor_build_version).nupkg
  name: BingImageDownload.$(appveyor_build_version).nupkg
deploy:
- provider: NuGet
  artifact: BingImageDownload.$(appveyor_build_version).nupkg
  on:
    branch: master
- provider: GitHub
  repository: BlythMeister/BingImageDownload
  artifact: BingImageDownload.$(appveyor_build_version).nupkg
  on:
    branch: master

